TYPE = "type"
NAME = "name"
POSITION = "position"
PREVIOUS_POSITION = "previous_position"
WALKABLES = "walkables"
INVENTORY = "inventory"
INTERACTABLES = "interactables"
GET_ACTION_NAME = "get_action_name"
